version: "3"
services:
  trss-yunzai:
    container_name: trss-yunzai
    image: registry.cn-hangzhou.aliyuncs.com/<namespace>/trss-yunzai-bot:3.1.0
    restart: always
    # ports:
    #   - "50831:50831"                                                 # 映射锅巴插件端口，格式"主机端口:容器内部端口"
    volumes:
      - ./yunzai/config/:/app/TRSS-Yunzai/config/config/                 # Bot基础配置文件
      - ./yunzai/genshin_config:/app/TRSS-Yunzai/plugins/genshin/config  # 公共Cookie，云崽功能配置文件
      - ./yunzai/logs:/app/TRSS-Yunzai/logs                              # 日志文件
      - ./yunzai/data:/app/TRSS-Yunzai/data                              # 数据文件
      # 以下目录是插件目录，安装完插件后需要手动添加映射（如有其他插件请自行添加）
      # 映射格式：./yunzai/plugins/<插件目录名>:/app/TRSS-Yunzai/plugins/<插件目录名>
      # - ./yunzai/plugins/example:/app/TRSS-Yunzai/plugins/example                          # 单js插件目录
      - ./yunzai/plugins/miao-plugin:/app/TRSS-Yunzai/plugins/miao-plugin                    # 默认映射喵喵插件
      # - ./yunzai/plugins/py-plugin:/app/TRSS-Yunzai/plugins/py-plugin                      # 新py插件
      # - ./yunzai/plugins/xiaoyao-cvs-plugin:/app/TRSS-Yunzai/plugins/xiaoyao-cvs-plugin    # 图鉴插件
      #### [警告] 受云崽架构和docker特性限制，使用锅巴插件安装的插件无法持久化，销毁容器后新安装的插件会消失，请谨慎使用 ####
      # - ./yunzai/plugins/Guoba-Plugin:/app/TRSS-Yunzai/plugins/Guoba-Plugin                # 锅巴插件
    depends_on:
      redis: { condition: service_healthy }
      go-cq: {}
    deploy:
      resources:
        limits:
          memory: 2G

  redis:
    container_name: trss-yunzai-redis
    image: redis:alpine
    restart: always
    volumes:
      # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中
      # - ./redis/config:/etc/redis/    # Redis配置文件
      - ./redis/data:/data
      - ./redis/logs:/logs
    # command: /etc/redis/redis.conf    # 取消注释以应用Redis配置文件
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s

  go-cq:
    container_name: trss-go-cqhttp
    image: ghcr.io/mrs4s/go-cqhttp:master
    restart: always
    volumes:
      - ./go-cq/config.yml:/data/config.yml
      - ./go-cq/device.json:/data/device.json
    
    
